- alias: 'Location: Trevin almost home'
  initial_state: 'true'
  trigger:
  - platform: zone
    entity_id: person.trevin
    zone: zone.home
    event: enter
  condition:
    condition: time
    after: 09:00:00
    before: '23:00:00'
  action:
  - service: notify.mobile_app_trevin_iphone
    data:
      message: Long press to announce arrival
      data:
        push:
          badge: 0
          category: arrival_trevin
          thread-id: arrival_trevin_action
  id: 17061c76080641d28fc8e328e2e983ba
- alias: 'Location: Allison almost home'
  initial_state: 'true'
  trigger:
  - platform: zone
    entity_id: person.allison
    zone: zone.home
    event: enter
  action:
  - service: notify.mobile_app_trevin_iphone
    data:
      message: Allison is almost home!
      data:
        push:
          sound: default
          thread-id: arrival_allison
  id: 4050a7f912004cbfb9296483d2cfa763
- alias: 'Alarm: Arm It'
  initial_state: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: ALARM_ARM
  action:
    service: notify.mobile_app_trevin_iphone
    data:
      message: Alarm Armed
      data:
        push:
          badge: 0
          thread-id: alarm_status
  id: 00f57ae6f5164bddb38ba38bbd886d1e
- alias: 'Alarm: Disarm'
  initial_state: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: ALARM_DISARM
  action:
    service: notify.mobile_app_trevin_iphone
    data:
      message: Alarm DisArmed
      data:
        push:
          badge: 0
          thread-id: alarm_status
  id: ae63be977daa4344a83a79cdb221435e
- alias: 'Notify (Phone + Alexa): Trevin close to home'
  initial_state: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: NOTIFY_AND_ANNOUNCE_ARRIVAL_TREVIN
  action:
  - service: notify.alexa_media
    data:
      target: group.alexa_all
      data:
        type: announce
      message: Daddy is almost home!
  - service: notify.iphone_all
    data:
      message: Trevin is almost home!
      data:
        push:
          badge: 0
          sound: default
          thread-id: trevin_arrival
  - service: notify.mobile_app_trevin_iphone
    data:
      message: 'DEBUG: Notify + Alexa announce Trevin arrival'
      data:
        push:
          badge: 0
          sound: default
          thread-id: trevin_arrival
  id: 5cb699114a1c4510b69728851281f380
- alias: 'Notify (Phone Only): Trevin close to home'
  initial_state: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: NOTIFY_ARRIVAL_TREVIN
  action:
  - service: notify.mobile_app_trevin_iphone
    data:
      message: 'DEBUG: Notified Trevin arrival by phone only'
      data:
        push:
          badge: 0
          sound: default
          thread-id: trevin_arrival
  - service: notify.iphone_all
    data:
      message: Trevin is almost home!
      data:
        push:
          badge: 0
          sound: default
          thread-id: trevin_arrival
  id: e34eee96aa08462faf2246148149a1f2
- alias: 'Notify (Phone): Trevin depart work'
  initial_state: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: NOTIFY_TREVIN_DEPART_WORK
  action:
  - service: notify.iphone_all
    data:
      message: omaha
      data:
        push:
          badge: 0
          sound: default
          thread-id: trevin_work_departure
  - service: notify.mobile_app_trevin_iphone
    data:
      message: 'DEBUG: Notify Trevin departure'
      data:
        push:
          badge: 0
          sound: default
          thread-id: trevin_work_departure
  id: fe9bfb897ee54376a752a7c947b9f5a0
- id: 771290b399dc4235b08d20531886d544
  alias: Start HomeKit
  trigger:
  - platform: event
    event_type: zwave.network_ready
  - platform: event
    event_type: zwave.network_complete
  - platform: event
    event_type: zwave.network_complete_some_dead
  action:
  - service: notify.telegram_chow_bot
    data:
      message: Z-Wave network ready, Homekit starting
  - service: homekit.start
    data: {}
  mode: single
- id: device_tracker_logging
  alias: 'Logging: Person location changes'
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - device_tracker.allison_iphone
    - device_tracker.trevin_iphone
  condition:
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
  - service: logbook.log
    data_template:
      name: 'Person: '
      message: '{{trigger.to_state.name}} changed from {{trigger.from_state.state}}
        to {{trigger.to_state.state}} by {{ trigger.to_state.attributes.source }}'
- alias: 'Notify: HASS Update notifications'
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: notify.mobile_app_trevin_iphone
    data:
      title: New Home Assistant Release
      message: Home Assistant  {{ states.updater.updater.state }}  is now available.
      data:
        push:
          sound: default
  id: d22a31f902fa4b0884f2e7f2daaafcd5
- id: '1594180518532'
  alias: Detect Attic Thermostat Mode Conflict
  description: Notify me if conflicting Attic Thermostat mode changes occur
  trigger:
  - entity_id: climate.attic
    platform: state
  condition:
  - condition: template
    value_template: '{{ states(''climate.attic'') != states(''climate.main'') }}'
  - condition: template
    value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  - condition: template
    value_template: '{{ trigger.to_state.state != "off" }}'
  action:
  - data:
      message: 'Attic thermostat conflict (Attic: {{ states(''climate.attic'') }},
        Main: {{ states(''climate.main'') }})'
    service: notify.mobile_app_trevin_iphone
- id: '1603744072253'
  alias: Kids Room Too Cold
  description: Turn on heater if falls below threshold
  trigger:
  - platform: numeric_state
    entity_id: sensor.kids_room_temperature
    below: '71'
    for: 00:02:00
  condition: []
  action:
  - type: turn_on
    device_id: 79ffa4a717c311eb8a47d38b94d19d31
    entity_id: switch.kids_room_heater
    domain: switch
  - service: notify.telegram_chow_bot
    data:
      message: '*Kids Room:* too cold ({{ states(''sensor.kids_room_heater'') }} degrees)

        *Heater:* turning on'
  mode: single
- id: '1603752769952'
  alias: Kids Room Maintain Temp (Night)
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kids_room_temperature
    below: '74'
  - platform: numeric_state
    entity_id: sensor.kids_room_temperature
    above: '76'
  condition:
  - condition: time
    after: '18:30:00'
    before: 06:00:00
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.kids_room_temperature
        below: '74'
      sequence:
      - type: turn_on
        device_id: 79ffa4a717c311eb8a47d38b94d19d31
        entity_id: switch.kids_room_heater
        domain: switch
    - conditions:
      - condition: numeric_state
        entity_id: sensor.kids_room_temperature
        above: '76'
      sequence:
      - type: turn_off
        device_id: 79ffa4a717c311eb8a47d38b94d19d31
        entity_id: switch.kids_room_heater
        domain: switch
    default: []
  - service: notify.telegram_chow_bot
    data:
      message: '*Maintain Room Temp (Night)*

        *Kids Room Temp:* {{ states(''sensor.kids_room_temperature'') }} degrees

        *Heater:* Turning {{ states(''switch.kids_room_heater'') }}'
  mode: single
- id: '1603853146730'
  alias: Kids Room Maintain Temp (Weekday)
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.kids_room_temperature
    below: '72'
  - platform: numeric_state
    entity_id: sensor.kids_room_temperature
    above: '74'
  condition:
  - condition: time
    after: 07:30:00
    before: '15:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.kids_room_temperature
        below: '72'
      sequence:
      - type: turn_on
        device_id: 79ffa4a717c311eb8a47d38b94d19d31
        entity_id: switch.kids_room_heater
        domain: switch
    - conditions:
      - condition: numeric_state
        entity_id: sensor.kids_room_temperature
        above: '74'
      sequence:
      - type: turn_off
        device_id: 79ffa4a717c311eb8a47d38b94d19d31
        entity_id: switch.kids_room_heater
        domain: switch
    default: []
  - service: notify.telegram_chow_bot
    data:
      message: '*Maintain Room Temp (Weekday)*

        *Kids Room Temp:* {{ states(''sensor.kids_room_temperature'') }} degrees

        *Heater:* Turning {{ states(''switch.kids_room_heater'') }}'
  mode: single
- id: '1603909881182'
  alias: Notify on kid's room temp change
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.kids_room_temperature
  - platform: state
    entity_id: switch.kids_room_heater
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
  action:
  - service: notify.telegram_chow_bot
    data:
      message: '*Kids Room Temp*: {{ states(''sensor.kids_room_temperature'') }} (Prev:
        {{ trigger.from_state.state }})

        *Heater*: {{ states(''switch.kids_room_heater'') }}'
  mode: single
- id: '1604296618320'
  alias: Notify on Master Bedroom Sensor
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.master_bedroom_temperature
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
  action:
  - service: notify.telegram_chow_bot
    data:
      message: '*Master Bedroom Temp*: {{ states(''sensor.master_bedroom_temperature'')
        }} (Prev: {{ trigger.from_state.state }})'
  mode: single
- id: '1604512615108'
  alias: Notify on Start/Shutdown
  description: ''
  trigger:
  - platform: homeassistant
    event: shutdown
  - platform: homeassistant
    event: start
  condition: []
  action:
  - service: notify.telegram_chow_bot
    data:
      message: 'Home Assistant: {{ trigger.event }}'
  mode: single
- id: '1605397615588'
  alias: 'Notify: HA Update Avail'
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: script.notify_all_engines
    data:
      title: System Notification
      message: Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version')
        }} is available.
  mode: single
- id: '1605688547007'
  alias: 'Notify: Alarm State Change'
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
  condition:
  - condition: template
    value_template: '{{ trigger.to_state.state != trigger.from_state.state }}'
  action:
  - service: notify.telegram_chow_bot
    data:
      message: 'Alarm: {{ trigger.to_state.state }}'
  mode: single
