homeassistant:
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.1.0/24
        - 10.241.0.0/16
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

#http:
#  ip_ban_enabled: true
#  login_attempts_threshold: 10

default_config:
config:
updater:
breaking_changes:

discovery:
#  ignore:
#    - plex_mediaserver

logger:
  default: info
#  logs:
#    custom_components.hacs: debug
#    hacs: debug
#    queueman: debug
#    AIOGitHubAPI: debug

cloud:
  alexa:
    entity_config:
      climate.attic:
        name: Attic Thermostat
        description: Thermostat in Attic Office
      climate.main:
        name: Main Thermostat
        description: Thermostat for house
      climate.kids_room:
        name: Kids Room Thermostat
        description: Heater for Kids Room

mqtt:
  broker: 192.168.1.161
  username: !secret mqtt_username
  password: !secret mqtt_password
  
life360:
  accounts:
    - username: !secret life360_username
      password: !secret life360_password

device_tracker:
  - platform: icloud3
    username: !secret email_trevin
    password: !secret icloud_password
    tracking_method: famshr
    config_ic3_file_name: /config/config_icloud3.yaml
#    track_devices:
#      - trevin_iphone > /local/images/trevin.png
#      - allison_iphone > /local/images/allison.png

alexa_media:
  accounts:
    - email: !secret email_trevin
      password: !secret amazon_password
      url: amazon.com
      include_devices:
        - "Kitchen"
        - "Living Room"
        - "Playroom"
        - "Master Bedroom"
        - "Upstairs Bathroom"
        - "Kid's Room"
        - "Attic"

# IFTTT
ifttt:
  key: !secret ifttt_key

notify:
  - platform: alexa_media
    name: alexa_media
  - name: iphone_all
    platform: group
    services:
      - service: ios_trevin_iphone
      - service: ios_allison_iphone
  - platform: telegram
    name: telegram_chow_bot
    chat_id: 391800743

panel_custom:
  - name: zwave-graph-panel
    url_path: zwave-graph
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:z-wave
    module_url: /local/zwavegraph3.js
    config:
      # ranker - pick one: network-simplex, tight-tree, longest-path
      ranker: network-simplex
      # edge_visibility - pick one: relevant, all
      edge_visibility: relevant
      # grouping - pick one: z-wave, ungrouped
      grouping: z-wave

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids:
      - 391800743
tts:
  - platform: google_translate
    service_name: google_say
    base_url: https://2rpnz0g8hfke9kct9lr3sy7045mtrld1.ui.nabu.casa

zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key

automation: !include automations.yaml
binary_sensor: !include sensors_binary.yaml
climate: !include climate.yaml
group: !include groups.yaml
homekit: !include homekit.yaml
ios: !include ios_categories.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
script: !include scripts.yaml
zone: !include zones.yaml

