- platform: template
  sensors:
    master_bedroom_motion:
      value_template: "{{ is_state('sensor.master_bedroom_burglar', '8') }}"
      friendly_name: "Master Bedroom Motion"
      device_class: motion
- platform: template
  sensors:
    playroom_motion:
      value_template: "{{ is_state('sensor.playroom_burglar', '8') }}"
      friendly_name: "Playroom Motion"
      device_class: motion
- platform: template
  sensors:
    kids_room_motion:
      value_template: "{{ is_state('sensor.kids_room_burglar', '8') }}"
      friendly_name: "Kid's Room Motion"
      device_class: motion
- platform: template
  sensors:
    foyer_motion:
      value_template: "{{ is_state('sensor.foyer_burglar', '8') }}"
      friendly_name: "Foyer Motion"
      device_class: motion      

- platform: template
  sensors:
    doors:
      friendly_name: "Doors"
      device_class: door
      value_template: >-
        {{ is_state('binary_sensor.front_door', 'on')
            and is_state('binary_sensor.side_door', 'on')
            and is_state('binary_sensor.back_door', 'on') }}

- platform: workday
  country: US
